name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  call-licensed:
    name: Licensed
    uses: actions/reusable-workflows/.github/workflows/licensed.yml@d468c63c53c1184242904d1a3ac74fd1081f36c8 # main
